/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.dangets.avroschemaevolution.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class User2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User2\",\"namespace\":\"com.dangets.avroschemaevolution.avro\",\"fields\":[{\"name\":\"first_name\",\"type\":\"string\",\"default\":\"unknown\"},{\"name\":\"last_name\",\"type\":\"string\",\"default\":\"unknown\"},{\"name\":\"favorite_number\",\"type\":[\"null\",\"int\"]},{\"name\":\"favorite_color\",\"type\":[\"null\",\"string\"]},{\"name\":\"d_name\",\"type\":[\"null\",\"string\"],\"default\":null,\"aliases\":[\"name\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence first_name;
  @Deprecated public java.lang.CharSequence last_name;
  @Deprecated public java.lang.Integer favorite_number;
  @Deprecated public java.lang.CharSequence favorite_color;
  @Deprecated public java.lang.CharSequence d_name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public User2() {}

  /**
   * All-args constructor.
   */
  public User2(java.lang.CharSequence first_name, java.lang.CharSequence last_name, java.lang.Integer favorite_number, java.lang.CharSequence favorite_color, java.lang.CharSequence d_name) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.favorite_number = favorite_number;
    this.favorite_color = favorite_color;
    this.d_name = d_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first_name;
    case 1: return last_name;
    case 2: return favorite_number;
    case 3: return favorite_color;
    case 4: return d_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first_name = (java.lang.CharSequence)value$; break;
    case 1: last_name = (java.lang.CharSequence)value$; break;
    case 2: favorite_number = (java.lang.Integer)value$; break;
    case 3: favorite_color = (java.lang.CharSequence)value$; break;
    case 4: d_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first_name' field.
   */
  public java.lang.CharSequence getFirstName() {
    return first_name;
  }

  /**
   * Sets the value of the 'first_name' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.first_name = value;
  }

  /**
   * Gets the value of the 'last_name' field.
   */
  public java.lang.CharSequence getLastName() {
    return last_name;
  }

  /**
   * Sets the value of the 'last_name' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.last_name = value;
  }

  /**
   * Gets the value of the 'favorite_number' field.
   */
  public java.lang.Integer getFavoriteNumber() {
    return favorite_number;
  }

  /**
   * Sets the value of the 'favorite_number' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(java.lang.Integer value) {
    this.favorite_number = value;
  }

  /**
   * Gets the value of the 'favorite_color' field.
   */
  public java.lang.CharSequence getFavoriteColor() {
    return favorite_color;
  }

  /**
   * Sets the value of the 'favorite_color' field.
   * @param value the value to set.
   */
  public void setFavoriteColor(java.lang.CharSequence value) {
    this.favorite_color = value;
  }

  /**
   * Gets the value of the 'd_name' field.
   */
  public java.lang.CharSequence getDName() {
    return d_name;
  }

  /**
   * Sets the value of the 'd_name' field.
   * @param value the value to set.
   */
  public void setDName(java.lang.CharSequence value) {
    this.d_name = value;
  }

  /** Creates a new User2 RecordBuilder */
  public static com.dangets.avroschemaevolution.avro.User2.Builder newBuilder() {
    return new com.dangets.avroschemaevolution.avro.User2.Builder();
  }
  
  /** Creates a new User2 RecordBuilder by copying an existing Builder */
  public static com.dangets.avroschemaevolution.avro.User2.Builder newBuilder(com.dangets.avroschemaevolution.avro.User2.Builder other) {
    return new com.dangets.avroschemaevolution.avro.User2.Builder(other);
  }
  
  /** Creates a new User2 RecordBuilder by copying an existing User2 instance */
  public static com.dangets.avroschemaevolution.avro.User2.Builder newBuilder(com.dangets.avroschemaevolution.avro.User2 other) {
    return new com.dangets.avroschemaevolution.avro.User2.Builder(other);
  }
  
  /**
   * RecordBuilder for User2 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User2>
    implements org.apache.avro.data.RecordBuilder<User2> {

    private java.lang.CharSequence first_name;
    private java.lang.CharSequence last_name;
    private java.lang.Integer favorite_number;
    private java.lang.CharSequence favorite_color;
    private java.lang.CharSequence d_name;

    /** Creates a new Builder */
    private Builder() {
      super(com.dangets.avroschemaevolution.avro.User2.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.dangets.avroschemaevolution.avro.User2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[2].schema(), other.favorite_number);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[3].schema(), other.favorite_color);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.d_name)) {
        this.d_name = data().deepCopy(fields()[4].schema(), other.d_name);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing User2 instance */
    private Builder(com.dangets.avroschemaevolution.avro.User2 other) {
            super(com.dangets.avroschemaevolution.avro.User2.SCHEMA$);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[2].schema(), other.favorite_number);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[3].schema(), other.favorite_color);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.d_name)) {
        this.d_name = data().deepCopy(fields()[4].schema(), other.d_name);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'first_name' field */
    public java.lang.CharSequence getFirstName() {
      return first_name;
    }
    
    /** Sets the value of the 'first_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.first_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'first_name' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'first_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'last_name' field */
    public java.lang.CharSequence getLastName() {
      return last_name;
    }
    
    /** Sets the value of the 'last_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.last_name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'last_name' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'last_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder clearLastName() {
      last_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'favorite_number' field */
    public java.lang.Integer getFavoriteNumber() {
      return favorite_number;
    }
    
    /** Sets the value of the 'favorite_number' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder setFavoriteNumber(java.lang.Integer value) {
      validate(fields()[2], value);
      this.favorite_number = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'favorite_number' field has been set */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'favorite_number' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder clearFavoriteNumber() {
      favorite_number = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'favorite_color' field */
    public java.lang.CharSequence getFavoriteColor() {
      return favorite_color;
    }
    
    /** Sets the value of the 'favorite_color' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder setFavoriteColor(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.favorite_color = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'favorite_color' field has been set */
    public boolean hasFavoriteColor() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'favorite_color' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder clearFavoriteColor() {
      favorite_color = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'd_name' field */
    public java.lang.CharSequence getDName() {
      return d_name;
    }
    
    /** Sets the value of the 'd_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder setDName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.d_name = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'd_name' field has been set */
    public boolean hasDName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'd_name' field */
    public com.dangets.avroschemaevolution.avro.User2.Builder clearDName() {
      d_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public User2 build() {
      try {
        User2 record = new User2();
        record.first_name = fieldSetFlags()[0] ? this.first_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.last_name = fieldSetFlags()[1] ? this.last_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.favorite_number = fieldSetFlags()[2] ? this.favorite_number : (java.lang.Integer) defaultValue(fields()[2]);
        record.favorite_color = fieldSetFlags()[3] ? this.favorite_color : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.d_name = fieldSetFlags()[4] ? this.d_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
